version: "3"

#docker exec -it kafka /bin/sh
  #sh-4.4$ kafka-console-producer --broker-list 0.0.0.0:9092 --topic messages
#docker exec -it kafka /bin/sh
  #sh-4.4$ kafka-console-consumer --bootstrap-server 0.0.0.0:9092 --topic messages --from-beginning

services:
  go-command:
    container_name: go-command
    build:
      context: .
      dockerfile: ./docker/command/Dockerfile
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: members
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - backend

  go-producer:
    container_name: es-producer
    build:
      context: .
      dockerfile: ./docker/producer/Dockerfile
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: members
    restart: always
    depends_on:
      - kafka
    networks:
      - backend

  go-query:
    container_name: go-query
    build:
      context: .
      dockerfile: ./docker/query/Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - kafka
    networks:
      - backend

  event-storage-redis:
    image: redis
    profiles: [ "event-storage-redis" ]
    container_name: event-storage-redis
    ports:
      - "6379:6379"
    networks:
      - backend

  query-storage-redis:
    image: redis
    profiles: [ "query-storage" ]
    container_name: query-storage-redis
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    environment:
      - REDIS_HOSTS=local:redis:6380
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: es-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: es-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - backend

networks:
  backend: